version: '3.4'

services:
    connectfour:
        image: connectfourclient
        build:
            context: client
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: development
        ports:
            - 4200:4200
            - 49153:49153
        volumes:
            - '/app/node_modules'
            - .:/usr/src/app/
    connectfourapi:
        image: connectfourapi
        build:
            context: api
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: development
        ports:
            - 5000:5000
        volumes:
            - .:/usr/src/app/
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - '/app/node_modules'
            - data:/data/db
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - data:/data/redis

volumes:
    data:
